language: c
compiler: gcc
branches:
  only:
    - master
os:
  - linux
  - osx

before_install: ./travis-scripts/before_install_${TRAVIS_OS_NAME}.sh
install:        ./travis-scripts/install_${TRAVIS_OS_NAME}.sh
script:         ./travis-scripts/script_${TRAVIS_OS_NAME}.sh

env:
  global:
  - secure: "Nz5FwSnUhdxPNrW5yBtpziZ6KXf1ya8GPEZihj7kNUuOQXhRKfdXqHIdshlcPyHMl/GtnsUs13FdcG11DnVU4wiULf21b+daJVcAvGoppYNnh7srjvOcW6YIKPwhTyIFLfeLXAM//yd5Xkfa5ZZDDHRcsie/y4gjnYiu0hMpX1E="
  - secure: "T+1j/Y/LS+Qph1qtg4KlVYcod4P9XASof0cM2mZR5CIy92m044KfIHvAFD9J/KcwgqsubS70zd9coZmgF/h3vlOU16v3GpthzdOPAITISSoAMp7iCB2R4LQS6matDzlBI5h3qTAcKvhWWWO8VjaoDBSXkjc1+ohKjPpIIrFntXE="
  - secure: "Kce1gRVaUMwmwBmFhhERHcyVrLzN4pX4cqXxYCts3DQRpnmplLUogDICGmSsIWGcyxZczvAihxrizoVvogm+Y1BnOvCR9v6prWep3u3iSGuw49Gx9lB3KXc8bJUmpx+QKIbYPEdR2woQYXMMwWozvPNVqyj4r0XLSqz+Y0kEa8A="
  - secure: "VaFWB4HgYHstn1YeKnN6OpEFPyxvbz4bbcd967vAPoPJwJBeXTknljZRl68J2KPAK/yMwb9qBJSMrtY48spwr7AAQCyKP7DTmI/ZG9QOUp3kdodkduRDxpwaZ1NnejaHlvTPhzNRwE+FlmSY5E2jwp0KRIIGfEsaJMvwvBXz73I="
  - secure: "HLAXkz2vxqWwuRtJVGjZ0iOdQYVu6vRgX/XXHkrE1hNQ+VydGuaHuz+bkMRPDroIdYMohV+Q1bd5+MatO7WPna8uMUzaz1nLNIg7Q8vi6TyitsSU5nouwDoeNuPyNND3bCQ/f5r/fJFCyw8OfqY0pSh+YMKYX7k3Me2A12+ziNc="
  - secure: "HpAyQq4CZZFw9IExzPV3BcsosevWA7cfC/L1XyODVkjj3zi96TKW8YejfgIQbsNo9MOyQfeRAQfhTvi9JjSaEdiDULvnexlMeyjKl2oQV8taa4wXuZ/phrqXeUrBPW6etrew7dmxqrOepsRPmVnKKlSNFh+X5zDcLCHDDyvFG00="
  - secure: "ZDeGZG2U6tzX/vK8YlO7eZc1qPoUTOdSb33Sbpvky+TKeSwzdByBmRX3KOW1xV6VRxG6MUM+2NirclyZyuoOnCvWETcWzdlzD1jPFXARdgYVlqB2F9hJHgyiKcGRGiPmkyfiRqof+zV/DEu73wiTffVO3V4BaI4C58bR08VHV1M="
  - secure: "THL71h7o9TRYvCETqo5LQfvdf/z0IffYA+TZ7oifofKrH7EPbgYIYqhcsJmteRk/MNUMoC4StqXaP37QzlMzLYNkXjqdw7n8C8y3+IOceRdn6ibctJ35rybzf177/gfEl+O7E4r1kI+MuzkmaTpfkRdAuosrA2TpkdQhgu1R8jg="
  - secure: "QaGcfGDeMg0q+LIyuO1U4kUXgTGp9BwOijcPSF1NAA/5yzeh1XexYgmqo41AEQrA5WCrTHzzTCp4+7oMOcXjBo56Ng3rbS+vY8h3R3rMIHYoCG87J9dN91aozNHT7IWJF7AgmMZP6WlncJs8o6KuZK3Pyx/HJZmDIRJbxT4i5Qo="
  - secure: "F40MESvocW3CaSAZ0b/R6naM0Z35h9s+h7n2TLnMTeUU9yTLn6CI5uV+5xpXGi9RDQFLCQjEkk9YTUgPkp/fyUQz2jdrAONPw09QWOPI8uaM/Y4/7zKJOSG/McH+xDc5yFQvGT9Rp3B5IMDFuxMJzfXFic80c/sqyY7j6RrI04k="
  - secure: "X0LEeuVOakdnnPCsi4lZ/VL1CdkKnGJe9Ilk+G3lD9PfQyAFQaHo4AIKeoowTbV3G1cs301nr1CZbDUmnyloN8GrKIl2CVpBzj/VQpXBkQz/fZ4r3KLJobh7Er3Ip7pJCCiDZPNfYA+Y6y/RCh9UeMN/SWfYzbA5RQYkMtCDDgk="
  - secure: "C1Z8WTF98zaY0u4NVxeBamGqEcVyDon74I7s+MEZBCM6LmRCzGSU0zTGlbcQVxu6/cVhb9uvrnuYPkXrLmZ/FSC+gu8FyhlzsHFGwB152fnj+hFnIJniF7T5lAfRIyoEDi7YA4Jkj6Wg/L+9tXtfqzskYKEY0rpBrFl+9vICVLg="
  - secure: "GGA4dHTHIkzAFD3enoGkpi1OOLUKLJTSi4tlV+C7jvZZEOW+Elw612ff5UneIAM733Laye3OE5sTzsl4AZ16U8cDqufxdc7+zqsTdBtI5Bg9m0A4wAUw5QK1bsZr/q4rWAZfE/7dM4/fm+fGzhULQw2K6f/54mgygYi1/zOPMb8="
  - secure: "e/whcRBe63KPBdgdrHD7kBpNVWWGX18cpluExhHYIYNgnusneHEZv+fn9R0+1WiiEw1DsUPhXPcIjtxf2DDEQu3duJ4TnPY5q7Pvb4P/lGnNZXR8jN/orvIj4O/VjtJV9EzqN/FuUig99GVO7oxVga67KQHMQTmeAXuSsHNPpTA="
  - secure: "ZOTchKw8dzq1Z9xungJuHy/WS1KN9L51B9nVQmv98gS3ZwQ7B3/blIovvDuRxdCMO8FXKz/9ErdjQcthhWLlfqhC70UQM8ErAPvMwwp+CylmnCVwnT7k0GVceAyguMZaJgfC3OS00qmNy/3aFmBQDq2LFkbmGI9SGtYLbSsHQSo="
  - secure: "YWy7BV2tCMXNtIF18esEZwKPvBd/GqVccqf1vhXkl9tRipNuB+m2ecXyeUHodKyZdixDWEEeEFIqzPZYOKOEOoHGYvElL55AiMrGFuy+zK9pdQog5QX2akfkS6Mof53V5R5VJ2b0fmjfvNNDbXm1hlqPghdUA9+Dfxr4pCm8dIM="
  - secure: "Hq+zjdDjU2DNwIJTqn1OunTpuipI4WlaTiOsDpQwbuZ0G1jqS3PMIXGN88ySv4zGuYZ6V6G3O2ANY547hhBmDwoZZwaakyvX7r6MfqAApnTdvFGMR6FRBOtJnJwk6GK6d6vwzNLvnULNM2MrHUyGGvXjY88LtBzmvFJR1Aiinxc="
  - secure: "ZZfdzn4MjQaHBACU8DZkpBL6GA+5Zc+h2LOhO/qqUQfH8Sw1GXlJ+JQdhNNJ7BNBx2AX8ZvKjaoI7Btfyxo7pzerwqCSjixoyyIE50Ew44qX0O/YZBGNKJFYsyeto+QS8rN4LnIEFogjNtufo+Bny4x+6IBu06idPB3EKP0/wXc="
  - secure: "M/CaEd5488IpttqTQ3B42LVp9URrhgs7nftYU0tOXYPeWlYhBcySRDs6IwGy/TbjbCo9o+0aLElJZ8bx3pIwpR3+WrjU9tv53LXF5FgQVKTHOLMlTxqP0sKQa74BiQhR2UzAZ0EhA4NrKTYXq97G45x36HU9wZ96dFadooa9Od4="
  - secure: "BtHdtI2Zru5HnU7zcVtXxXd69/sAjrC0LbaZgtCU7V6UFha3c5okD2oVbQ3GQ45hJrnClQ52R9m0OMcVl4R2jG5PpAHmTQahSbGEb9VNl7mDsqUGqbaCpulTiWJ5O23YWal/M52u52uY7Yrm8h8O2Logg8z+8NWiw81+juKbx2U="
  - secure: "dMh+fzepaN92AU1IK7N2IqU/XgEZjXwrD3j4RNK9XXzWLelfkCu8y5uT53QpJ0HgqyOrY5uV3aPrPRQROjGJR+nbX25Uf2f7uoD2SBKh+2FjHMZVU6xwp9FrElULU+Cp9r6jPIya4Cc7+h+zsKTOSOJ8SixXkl9IT+6acgfe0OA="
  - secure: "gSUtLzTo3Aow3XV2BOZenJS0QExxe7zoa45iQfzpFlqpVpjC3eRsIKlQd99RIxVHnoupW7QTtbYPMlQl/OfzCcpkXJB3T3jR5+5hcxyiljryqccr07//4vbvZ1XjtJn8LfjzBaI3gu7WoD7SdY/NpbCKPIzqYDTNtN3eZisT3xo="
  - secure: "ahLh7dCBecNnbbRLXxhFJOddh0Y3FYRam+HvUhk5Em+e143/zrP7tqK8CC+mNk3bX1PYx9lfwsacrrnDF2ZcwhV2PUq0kz3/1Xa/ZiEe9u+LELUFQdNGECt9gafYFVOJuyG1u8DcwhAecxjt3NWTnivc3LBsKTZ9WL5wOTaMOJI="
