language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autotools-dev libjpeg-dev libtiff4-dev libpng12-dev libgif-dev libxt-dev libfreetype6-dev autoconf automake libtool bzip2 libxml2-dev libuninameslist-dev libspiro-dev python-dev libpango1.0-dev libcairo2-dev chrpath
install:
  - wget 'http://download.zeromq.org/zeromq-4.0.1.tar.gz' -O - | tar -zxvf -
  - pushd zeromq-4.0.1 && ./configure --prefix=/usr && make && sudo make install && popd
  - wget 'https://bitbucket.org/sortsmill/libunicodenames/downloads/libunicodenames-1.1.0_beta1.tar.xz' -O - | tar -Jxvf -
  - pushd libunicodenames-1.1.0_beta1 && ./configure --prefix=/usr && make && sudo make install && popd
  - apt-get source libfreetype6
script:
  - ./autogen.sh
  - ./configure --prefix=/usr --withou-freetype=source=../freetype-2.4.12
  - make
  - tests/link_test
  - sudo make install
  - fontforge -version
branches:
  only:
    - master
