language: c
compiler: gcc
branches:
  only:
    - master
os:
  - linux
  - osx

before_install: ./travis-scripts/before_install_${TRAVIS_OS_NAME}.sh
install:        ./travis-scripts/install_${TRAVIS_OS_NAME}.sh
script:         ./travis-scripts/script_${TRAVIS_OS_NAME}.sh

env:
  global:
  - secure: "WHw9y/mo8TPeVs+xeYYJjmy0sYzT0zysvVwm6V+O+/Vh2bcIgwz599AzP35hpXlmFx6wbpcr5Ie5xshJLZpbXZhmIrdrNzbALAWtL4BA44+ry0fZgT3iqrNCiwpRUfZZvF63C8/Ch32a500CUX41yocZ0lk+FGw97NPg4ZiyNnk="
  - secure: "Fm22Ct0XOcC6Vwpfh3wihfDVSnXG+YYIfboARtAxsRGZiDm0523gZni9e5D/N3lubRq7pR8wTBr1uiJzQlnTLZZdlYD4lVgGtLbp7dofE9mdqImr0YazxtYID1zgpMrnxnDCLEj+ifznGsVt307JApACNGZ3T9lobUpuC+7Uelo="
  - secure: "bpEh8t4C2aJmQwUqP41/SzOUrE4PkUGNlDJXjT35UArXXaqNE9SQOQxGeqBNG6oFFKB0HWW1ISvYu6f7vOcDog9fQxs6RiWsvFr/k/9lpWgnj6kL4qMl5FYaBJ1xDJyimbk2F1AbOrhVxOLGmfJ5uR7I5rp5Ohbn6eZz022W8Gc="
  - secure: "Yy1pYJfAtx240z38u///I573qhA1j0LrEQpafF6VTmv5aE+U6+UerTPF786t3OzUvQnKnf2MeZs8lRKBQyvNOFGKll8HfGNj9NFgc1MJQSaahT/Wwrp6OA4eqOY0yQ0KbQTNJOMd4l1kkRu4/S12rq/B0BpQ+DLtM3mH/8pA42E="
  - secure: "NEWRK6CewtfkcqwSMKz2TmmSIG54lNvI1bgMaBxI/uvzJ4glQyz7ml3z1B2Hvf1OzLsZiRjQSWIE4Ear5nseTA077WqZNXoT9xU6pB25haRq2M/ixzM5DRr4GdyV7H2ZL5WrNem5LSTfApO2Oo0zp2Uyr+s31WyJSXvcVGTGoFM="
  - secure: "QInAI+eaWzcGXmmkb79MAGUSn1wvbrogekEh2Vy9jlojoRJTnDwlKSaCst2Jm+GHo05kW8H4v0uXBtbvEYrgFJXigrxABFWOATb8K9q5IpNP4ppTMFV+MhYo0UGNkDPXnsonfE0MM/0UhBu3RqmSTmTU7GKCe2TUcMVF2F3aTIQ="
  - secure: "N2Uj+08Wlsp5jo30j8aZZ/0jYseHSSnkvNd9EmTXQB/AtEECCIMfPIu4kLgyGdKbG658qD4roMik0KTiUJKjFTOscmThEniMbFUm+YY8QTPs0IUJhAHE3NC9SZXUWXAs6LCrgKzkbCMyUgrRO+BajySteCwdpVqCnqoajCioC58="
  - secure: "FfK0Hp+Ta0c0n2mdBTrmxwIzG0QNi9WxEpCilRhfD5Errq36ZSWuMKTXg4lC7gMSwrgJG9qT8uhtJ/m9mwn/zML2MrbazqDflIu5giiclR0dHYH7QoeYCzZygbUriE/xHieMl4sRB5nVl/iKCK3XSVvUgA6Odk4c+YJ2db/Metw="
  - secure: "R2kafVotjQ9NfubVAOXMv3MH9c3UPZYdAV6jIAEXOttUgVEvE/vPJaLDttwaCoZy7+XLqRf4RZaQF5DuoJwjB4H5qqKgCb8eCNsBjGDTQgqvasPm6kVPsDIjXFdtqBGTL+Wd2Yp+y35drOatFZNlb8d2/oLmhFDBsaXnkgKnJWM="
  - secure: "fteknezdwWkQYtaPIN4qs54YH7Bx1wRMK8S9ZRWK0usSgUmzqEPd8lp9rizjvORD6C+WRU/+KAy7RDgRAenaJABWRo5eBZXsrw88OQ5zn5nJzgPoh755a+ycU/I10W+HcOe2tltbGzebvM/GE4lxKTGoiIk8AX8P5QAeWrmn55Q="
  - secure: "eFqyiuckEdTYmK0Qu6czta0+TVqP50s0a6eMikOlRkJSuU4SbBExi/vfQlorUVC4qk1/lTFis6EQ4Irdh20Qyk04puxjomABn45yv0Zm258IyUTI55Lj9y+2zoN0/xnLKEg/15HvRfndHmFTOTdzp+fXIy4X6xmbUR2Fn+r67Pw="
  - secure: "CLEc9jYW1y/G5fSNk7MYF4qmFDe53drjfQ3sXuME3//cKZq6SczyLwk2DftbHk/hR7KdGB8qtYmm7I1rYNAbBKZzcC8uYmkPx9tq1CZLgKg3n3fbuValE3beGeifeO/Y/OlwhwSNgIScd42CjiH29J42vgNFF/QvIWtVzrVkk2c="
  - secure: "WtNH0DB3IwUsysyAQH/IEEquSHrdIlNz6Y0fb5YIbB1XMBmsXzejFlE6KCjmzVbVOvgeFMK4aXPoeokJjP4vykGDwx9ISfhjYy5BO6WiDqsE+XnWb07/EakslywuPoAdPsLerAnr5jJ/6BM4Ia43m6bAHUQ5EhyTQ0iE77Rv7o8="
  - secure: "LrGS6PifDJgwg0ZVQkHhFp/VyGAk1dyWAXYw/0OyMBIQw0TyB/uJt0RwJkOQlE4oCJxdoQexaGAK13giOJkTrt4tGAdRrVzhFeUSd7rGlfLo9KklpL36SNabnwf/ZOA+x1sKDvMXB7pRDA+Jl79kEFtdjv7UPsBb8hYmv8pS+Es="
  - secure: "JpHE7/hLicCEUF02nCg1r6vZjInYH2BNNb8DiePxID6tWABKmoIyjgoe86lLDKoehXeAXmSaJKHjuog9qi+AgsSr7RUsGDmwLLBoP5CczpaQ7Pcm4krRPdHixRt/FtugAQTFlE84xgsxnJl6X3KemZfOo2x+paF8Nf4AXse/et4="
  - secure: "Pb19d4Zgw994LEDuwx8jJrSljcJOpFlgsatO7a5DP8jMOm5KSnYMzWxuNQoBHN/AkkHomUGYZ3Jbs+M8jshxpAen0YcqfIx4CkgvX6IvIECMN5WONoVHTToIcsYrlvQdhegxWBREQoT6myi2lM3LrdfoRC6LDC6ZMmQPpLuTmyE="
  - secure: "PGiNhNngiqHL0UI32jt4Gx2lAsxR3rfu2n03m16oX9eYTy7Ec9dCFF/2/lCI9RoCHZbpHnKzWDl6DdOlBF7BY/1fQVk9RIcU6kKKSzhZH9ugHGjuI9Nb5DqRXyAqkSemMsSgkdN2vfqbLmI7aC6FRVWHwPK0Fq+7TW/bV4Bqa5E="
  - secure: "KQ30RBjon6E3y+TAQHqsMuOtBeAg7Pc1t2h68xw3vWjYpYUjzP/PwUJ+bcUUsLTB35gj6U7dtaAEXzrx60rXiRg5wfmyTNF/3wu+YkELqKw0hDjiDqAabHSOmitowIrYP8gA4HiU4CQr8XJEiMB3wDI2Kxkwyv5l0t1xGuL64nA="
  - secure: "cm//pad+4XU2IGxnjyiDc22bH8sgxH5DqY95PZEg2O+ZOUNi/fUoyQpZ7xTOzpIiwOhXhdROi4WSknm5WDcs3vvrv1D2MgAHFzlrBzKkKzytKWfiZn1kJLrIX5QbneWCtC7hTXh4OHJnocV92Mav1zJEfE2lkVZ1DidZ75mwLt0="
  - secure: "YKILeaM9ALulVYjGyMJMjmqQzlOfOkKmVRL1j6OXcFR3lC1xDihQlWBDhCdJkcfbjTvH2uNogbVx+5Z2PX3qCMnybI/baXmJkbIb+WE+ircuzWEWsWjwHN0F42mWPhRLteiUhF+WKY1zND2gUC61Eslu0kxe1KwPxLVBXiwxKPU="
  - secure: "Yz+0GvSXkFid0/ec9pia6CECzAe+E/k9LKt4MyRlzW5SNC5MVKvIS+4zheVDF1HXLjvV2FhhhTg6zaPqPjZ9mRi8yV97DQuBw4dZzr5tjds8BkHJYNCm9pR5mhRm9h3hC9p3BA9LzunIXe3BWb/nvDU0i4qEsZipna92snSiDSY="
  - secure: "fza9ttvRYtVRNzmlVgQ1IuF+BvRCyX2hf021QNtLuIkUj6v59ZiC2vJo+Xie/5Sm/qYLn1tDCoDnNybWbqiFXJfR1ANYm6dX5o8GUpfgcbEq0LwMYZgJLAuPJtSVW2jP4I7ILJH3hlq/XWmA5n5G1wPVArs974ANYhZYlqBX76M="
  - secure: "L90GP14evg/VBRtXpdZtbUZLkwFVSjtNaTFqbbpyTmDqCcY+BI0ZgpGzMX6+xIfULJ9rYEdhqGm9+KXrsE+HHJAVkD6Dtq7JQ5QAjpv13zG1zdL4tJi6Z0n9XQbKiDCFLq9GG6L7DunGWsGoF+st4KWV6mjnZoDVqFbfbR6khmE="
